export const tours = [
	{
		id: 1,
		name: "Bali Adventure",
		image: "https://images.unsplash.com/photo-1558005530-a7958896ec60?w=800",
		price: 1299,
		info: "Experience the magic of Bali with this 7-day adventure package. Visit ancient temples, relax on pristine beaches, explore rice terraces, and immerse yourself in the local culture. Package includes luxury accommodation, guided tours, and traditional spa treatments.",
	},
	{
		id: 2,
		name: "Paris Explorer",
		image: "https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800",
		price: 1899,
		info: "Discover the city of love with a 5-day Paris experience. Visit the iconic Eiffel Tower, explore the Louvre Museum, stroll through charming Montmartre, and enjoy authentic French cuisine. Includes boutique hotel stay and Seine River cruise.",
	},
	{
		id: 3,
		name: "Egyptian Wonders",
		image: "https://images.unsplash.com/photo-1568322445389-f64ac2515022?w=800",
		price: 1599,
		info: "Uncover the mysteries of ancient Egypt in this 8-day tour. Visit the Great Pyramids of Giza, cruise down the Nile River, explore the Valley of the Kings, and experience the bustling markets of Cairo. Includes guided tours and luxury Nile cruise accommodation.",
	},
	{
		id: 4,
		name: "Japanese Heritage",
		image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
		price: 2299,
		info: "Immerse yourself in Japanese culture with this 10-day journey. Experience Tokyo's modern wonders, visit historic Kyoto temples, stay in a traditional ryokan, and witness the beauty of Mount Fuji. Includes bullet train passes and tea ceremony experience.",
	},
	{
		id: 5,
		name: "Machu Picchu Trek",
		image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
		price: 1799,
		info: "Embark on a 6-day adventure to the ancient Incan citadel. Hike the famous Inca Trail, explore the Sacred Valley, and discover the mysteries of Machu Picchu. Package includes guided tours, camping equipment, and traditional Peruvian experiences.",
	},
	{
		id: 6,
		name: "Santorini Escape",
		image: "https://images.unsplash.com/photo-1570077188670-6a96607efd7b?w=800",
		price: 2099,
		info: "Experience the stunning beauty of Santorini in this 5-day luxury retreat. Stay in cave hotels, watch famous sunsets, explore white-washed villages, and sail the caldera. Package includes wine tasting, cooking class, and private transfers.",
	},
	{
		id: 7,
		name: "Maldives Paradise",
		image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
		price: 3299,
		info: "Escape to paradise with this 7-day Maldives package. Stay in overwater villas, snorkel in crystal clear waters, enjoy spa treatments, and witness spectacular marine life. All-inclusive package with seaplane transfers.",
	},
	{
		id: 8,
		name: "African Safari",
		image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800",
		price: 4299,
		info: "Experience an unforgettable 8-day safari in Tanzania. Witness the Great Migration, spot the Big Five in Serengeti, and visit Ngorongoro Crater. Luxury lodge accommodation and professional wildlife guides included.",
	},
	{
		id: 9,
		name: "New Zealand Adventure",
		image: "https://images.unsplash.com/photo-1469554466046-db86ca300199?w=800",
		price: 2899,
		info: "Discover New Zealand's South Island in 10 days. Experience Queenstown's adventures, visit Milford Sound, hike glaciers, and enjoy world-class wine. Includes accommodation, activities, and domestic flights.",
	},
	{
		id: 10,
		name: "Northern Lights Hunt",
		image: "https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=800",
		price: 2599,
		info: "Chase the Aurora Borealis in Iceland for 6 days. Stay in glass igloos, soak in geothermal pools, explore ice caves, and witness stunning waterfalls. Includes winter gear and professional photography guides.",
	},
];
